[package]
name = "freopen_chat_bot"
version = "0.1.0"
authors = ["Aleksei Zolotov <freopen@freopen.org>"]
edition = "2018"


[dependencies]
anyhow = "1.0.39"
bytes = "1.0.1"
chrono = "0.4.19"
dotenv = "0.15.0"
env_logger = "0.8.3"
futures = "0.3.13"
image = { version = "0.23.14", features = ["jpeg", "png"] }
lazy_static = "1.4.0"
log = "0.4.14"
regex = "1.4.5"
reqwest = { version = "0.11.2", features = [
  "native-tls-vendored",
  "gzip",
  "brotli",
  "multipart",
  "json",
] }
serde_json = "1.0.64"
tokio = { version = "1.3.0", features = ["full"] }
