[package]
name = "freopen-chat-bot"
version = "0.1.0"
authors = ["Aleksei Zolotov <freopen@freopen.org>"]
edition = "2018"


[dependencies]
bytes = "1.0.1"
futures = "0.3.13"
image = "0.23.14"
reqwest = { version = "0.11.2", features = ["gzip", "brotli", "multipart", "json"] }
tokio = { version = "1.3.0", features = ["full"] }
serde_json = "1.0.64"
log = "0.4.14"
env_logger = "0.8.3"
