[package]
name = "freopen_chat_bot"
version = "0.1.0"
authors = ["Aleksei Zolotov <freopen@freopen.org>"]
edition = "2018"


[dependencies]
anyhow = { version = "1.0.40", features = ["backtrace"] }
bytes = "1.0.1"
chrono = "0.4.19"
dotenv = "0.15.0"
env_logger = "0.8.3"
futures = "0.3.13"
image = "0.23.14"
lazy_static = "1.4.0"
log = "0.4.14"
regex = "1.4.5"
reqwest = { version = "0.11.2", default-features = false, features = [
  "rustls-tls",
  "gzip",
  "brotli",
  "multipart",
  "json",
] }
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
serenity = { version = "0.10.5", default-features = false, features = [
  "client",
  "gateway",
  "rustls_backend",
  "model",
] }
teloxide = { version = "0.4.0", features = ["auto-send", "macros"] }
tokio = { version = "1.4.0", features = ["full"] }
tokio-stream = "0.1.5"
