name: Audit deps

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install audit tool
      run: cargo install --force cargo-audit

    - name: Cargo audit
      run: cargo audit